import { Geist, Geist_Mono } from "next/font/google";
import {MainRootHeader} from "../componets/utilities"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bastiasa",
  description: "Generated by create next app",
};

export default function RootLayout({ children}) {
  return (
    <html lang="en">


      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainRootHeader></MainRootHeader>

        <main
          style={{
            width: "100%",
            maxWidth: "700px",
            margin: "20px auto",
            padding: "20px"
          }}>
          
        {children}

        </main>


      </body>
    </html>
  );
}
